name:
on: [push, workflow-dispatch]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo-hello 
        run: echo "Hello World"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: echo "Goodbye!"